spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: zsf997784022
    driver-class-name: com.mysql.cj.jdbc.Driver